### ISSUE TITLE
Curious on 201 section

### ISSUE THREAD

**Issue by stefensuhat** [adnan-kamili/rest-api-response-format#1]
Thanks for the gist. I have 2 questions: 

1. On success `201` you send back `message` instead of the created object. Why?
2. What if I want to show to user alert "Successfully created" or "Successfully updated"?. Should the message come from server or client side?

**Comment by adnan-kamili** [comment]
Hi @stefensuhat,

> On success 201 you send back message instead of the created object. Why?

If you noticed the **Location** header in the response, it contains the url which can be used to get the created resource, which allows for getting the created resource on demand, because every consumer of API may not need the resource immediately.

> What if I want to show to user alert "Successfully created" or "Successfully updated"?. Should the message come from server or client side?

API client (web app, mobile app) may need different types of messages. Server can send a default message which can be used client side, or u can use status 201 to determine success and show any specific message client side.
